using BSplineKit
using Roots: find_zero, Bisection
using GaussQuadrature: legendre

const BSK = BSplineKit


###############################################################
# Breakpoint and Knot Generation
################################################################

"""
symmetric_rice_breakpoints(degree::Integer, α::Real, N::Integer) -> Vector{T}

Rice power partition on [0,1], symmetric about 1/2, for endpoint
singularities ~ x^(-α) at x=0 and (1-x)^(-α) at x=1.

Uses q = (2(degree+1) + 1) / (2α + 1) and maps u=i/N by
  x(u) = 0.5*( (u/0.5)^q )          for u ≤ 0.5
         1 - 0.5*( ((1-u)/0.5)^q )  for u >  0.5

- degree : B-spline degree (cubics are degree=3)
- α : exponent (> -1/2 so 2α+1 > 0)
- N : number of elements (returns N+1 breakpoints)
"""
function symmetric_rice_breakpoints(degree::Integer, α::Real, N::Integer)

    k = degree + 1
    k ≥ 1     || throw(ArgumentError("Require degree ≥ 0, got $degree"))
    N ≥ 2     || throw(ArgumentError("Require N ≥ 2, got $N"))
    α > -0.5  || throw(ArgumentError("Require 2α+1 > 0 for a valid q, got α=$α"))

    T = float(typeof(α))
    q = (T(2k) + one(T)) / (T(2)*T(α) + one(T))

    u    = collect(range(zero(T), one(T); length=N+1))
    x    = similar(u)
    half = T(0.5)

    @inbounds for i in eachindex(u)
        ui = u[i]
        if ui ≤ half
            x[i] = half * ((ui/half)^q)
        else
            x[i] = one(T) - half * (((one(T)-ui)/half)^q)
        end
    end

    x[1] = zero(T); x[end] = one(T)   # exact endpoints
    return x
end



"""
    hybrid_equidistribution_breakpoints(α, ε, n_outer, ::Type{T}=Float64) -> Vector{T}

Hybrid breakpoint sequence for a cubic B-spline L² approximation of the noisy symmetric
Pomeau--Manneville invariant density. The breakpoints in `[0, 1/2]` are constructed from
two pieces and then reflected over `x = 1/2`.

- **Inner region** `[0, L_ε]`: breakpoints are geometrically graded. The mesh ratio
  `r ∈ [1, 2]` is chosen so that the geometric series exactly covers `L_ε`, while the
  spacing at the matching point `L_ε` agrees with the first outer interval.

- **Outer region** `[L_ε, 1/2]`: breakpoints are generated by the de Boor L² power
  partition, equidistributed with respect to the monitor function
  `x^((1 - 2α)/9 - 1)`. Equivalently, the outer breakpoints are

      x_i = (L_ε^γ + (i/n_outer) * ((1/2)^γ - L_ε^γ))^(1/γ),
      γ = (1 - 2α)/9.

  When `γ = 0`, corresponding to `α = 1/2`, this is replaced by the limiting
  log-linear spacing

      x_i = exp(log(L_ε) + (i/n_outer) * (log(1/2) - log(L_ε))).

The matching point `L_ε` is the boundary-layer scale. It separates the inner plateau
region from the outer power-law region.

Arguments:
- `α`       : PM exponent, with `0 < α < 1`
- `ε`       : noise parameter
- `n_outer` : number of equal-mass intervals in `[L_ε, 1/2]`; contributes
              `n_outer - 1` interior outer breakpoints
- `T`       : floating-point precision, e.g. `Float64`, `Double64`, `BigFloat`
"""
function hybrid_equidistribution_breakpoints(
    α::Real, ε::Real, n_outer::Integer, ::Type{T}=Float64
) where {T<:AbstractFloat}

    0 < α < 1     || throw(ArgumentError("Require 0 < α < 1, got α=$α"))
    ε > 0         || throw(ArgumentError("Require ε > 0, got ε=$ε"))
    n_outer ≥ 2   || throw(ArgumentError("Require n_outer ≥ 2, got n_outer=$n_outer"))

    α_T  = T(α)
    half = one(T) / T(2)

    L_ε = Utils.boundary_layer_scale(α_T, T(ε))
    γ   = (one(T) - T(2) * α_T) / T(9)

    # Outer region: de Boor L² power partition on [L_ε, 1/2].
    outer_breakpoints = if iszero(γ) || abs(γ) ≤ sqrt(eps(T)) || !isfinite(one(T) / γ)
        log_L = log(L_ε)
        log_h = log(half)

        T[
            exp(log_L + T(i) / T(n_outer) * (log_h - log_L))
            for i in 1:n_outer-1
        ]
    else
        L_ε_γ = L_ε^γ
        Δ_γ   = half^γ - L_ε_γ

        T[
            (L_ε_γ + T(i) / T(n_outer) * Δ_γ)^(one(T) / γ)
            for i in 1:n_outer-1
        ]
    end

    h_outer0 = outer_breakpoints[1] - L_ε

    # Inner region: geometric grading on [0, L_ε], matched to the first outer spacing.
    inner_breakpoints = if L_ε ≤ eps(T) * half
        T[]   # Degenerate inner region: L_ε is numerically indistinguishable from zero.
    elseif h_outer0 ≥ L_ε
        T[]   # A single interval [0, L_ε] is already no larger than the first outer interval.
    else
        n_inner_intervals = ceil(Int, log2(one(T) + L_ε / h_outer0))

        ratio = L_ε / h_outer0

        # Below this |r - 1|, the geometric sum (r^n - 1)/(r - 1) is evaluated by
        # its r → 1 limit to avoid 0/0. Value chosen (not derived); kept fixed for
        # reproducibility of previously generated meshes.
        r_unit_tol = T(1e-10)

        r = if n_inner_intervals == 1 || ratio ≤ T(n_inner_intervals)
            # Uniform spacing already keeps each inner step no larger than h_outer0.
            one(T)
        else
            geo(r) = abs(r - one(T)) < r_unit_tol ?
                T(n_inner_intervals) :
                (r^n_inner_intervals - one(T)) / (r - one(T))

            find_zero(r -> geo(r) - ratio, (one(T), T(2)), Bisection())
        end

        pts = T[]

        for k in 1:n_inner_intervals-1
            S_k = abs(r - one(T)) < r_unit_tol ?
                T(k) * h_outer0 :
                h_outer0 * (r^k - one(T)) / (r - one(T))

            push!(pts, L_ε - S_k)
        end

        sort!(pts)
    end

    # Assemble the left half and reflect symmetrically over x = 1/2.
    left_half = vcat(
        zero(T),
        inner_breakpoints,
        L_ε,
        outer_breakpoints,
        half,
    )

    right_half = one(T) .- reverse(left_half)

    breakpoints      = vcat(left_half, right_half[2:end])
    breakpoints[1]   = zero(T)
    breakpoints[end] = one(T)

    return breakpoints
end


"""
    build_stacked_knot_vector(breaks, stack_points; p=3, atol)

Expands a strictly increasing vector of breakpoints into a valid knot vector,
stacking knots to multiplicity p+1 at the endpoints and at any specified `stack_points`.
If 'x' is a stack point then no b-spline will have support that straddles 'x'.

Arguments:
- `breaks` : strictly increasing vector of breakpoints (e.g., from `hybrid_equidistribution_breakpoints`)
- `stack_points` : vector of points at which to stack knots
- `p` : spline degree
- `atol` : absolute tolerance for determining if a breakpoint matches a stack point
"""
function build_stacked_knot_vector(
    breaks::Vector{T}, 
    stack_points::Vector{T}; 
    p::Int=3, 
    atol::T=eps(T)
) where {T<:AbstractFloat}

    knots = T[]
    mult  = p + 1

    # Fully stack left endpoint
    append!(knots, fill(breaks[1], mult))

    # Add interior knots, stacking if they match our target points
    for i in 2:(length(breaks)-1)
        pt = breaks[i]
        
        is_stacked = any(s -> abs(pt - s) <= atol, stack_points)
        if is_stacked
            append!(knots, fill(pt, mult))
        else
            push!(knots, pt)
        end
    end

    # Fully stack right endpoint
    append!(knots, fill(breaks[end], mult))

    return knots
end



############################################
# SingleBSpline Construction Utilities
#############################################

"""
    struct PolyPiece{T,N}
A single polynomial piece of the B-spline on ([0,1]).

Type Parameters:
- `T` : numeric type (e.g., Float64, BigFloat)
- `N` : number of coefficients (= degree+1)

Fields:
- `a,b`    :: T,T        # endpoints in [0,1]
- `x0`     :: T          # center point of support for monomial expansion: (a+b)/2
- `coeffs` :: NTuple{N,T}  # coefficients (c₀, c₁, …, c_{N-1}) for centered monomial basis
                          # on [a,b]:  S(x) = ∑_{k=0}^{N-1} c_k * (x - x0)^k
"""
struct PolyPiece{T,N}
    a::T
    b::T
    x0::T
    coeffs::NTuple{N,T}
end

# constructor for empty coeffs (filled with zeros). fill later with with_coeffs
@inline _mk_piece(::Val{P}, a::T, b::T) where {T<:AbstractFloat,P} =
    PolyPiece{T,P+1}(a, b, (a+b)/T(2), ntuple(_->zero(T), P+1))


# struct is immutable, once coefficients are computed copy into new struct with coeffs
@inline with_coeffs(pp::PolyPiece{T,N}, c::NTuple{N,T}) where {T<:AbstractFloat,N} =
    PolyPiece{T,N}(pp.a, pp.b, pp.x0, c)

    
"""
    poly_intervals(bfun) -> Vector{Tuple{T,T}}

Returns the intervals on which the B-spline `bfun` is a single
polynomial piece for a periodic or non-periodic basis. 

**WARNING: Other Functions in this package are not designed to support periodic splines**

- Works for periodic and non-periodic bases (BSplineKit) of BSplines on [0,1]
- For periodic splines all pieces are mapped back to [0,1] via mod 1.
- Requires the knot vector to include 0 and 1; zero-length spans are omitted.

Arguments
- `bfun`: A B-spline basis function, see examples

Returns
- Vector of `(a,b)` tuples delimiting polynomial support intervals.

# Examples
B = BSplines.BSplineBasis(BSplineOrder(4), breakpoints)
bfun = B[1]
ivs = poly_intervals(bfun)
"""
function poly_intervals(bfun)

    rng = BSK.BSplines.support(bfun)  # range of knot vector indices where bfun is nonzero
    _basis = BSK.BSplines.basis(bfun)
    T     = eltype(BSK.knots(_basis))
    τ     = collect(T, BSK.knots(_basis)) # knot vector

    T(0) in τ && T(1) in τ || throw(ArgumentError("Knots must include 0 and 1"))

    spans = Tuple{T,T}[]
    for k in rng.start:rng.stop-1
        push!(spans, (τ[k], τ[k+1]))
    end

    filter!(x-> x[1] != x[2], spans) # Filter out zero-length spans

    all(a < b && !(a < 0 && b > 0) && !(a<1 && b>1) for (a, b) in spans) ||
        throw(ArgumentError("Spans must be non-degenerate and not cross 0/1"))
    map!(Utils.mod_interval, spans, spans) # map back to [0,1]
    sort!(spans; by = t -> t[1])

    return spans
end


"""
    polynomial_pieces(bfun) -> Vector{PolyPiece{T}}

Return all polynomial pieces of a single B-spline `bfun` without centered monomial
coefficients. Assumes that bfun is from a BSplineKit basis on [0,1] with knots including 0 and 1. See
`poly_intervals` for details on interval construction.
"""
function polynomial_pieces(bfun, ::Val{P}) where {P}
    basis = BSK.BSplines.basis(bfun)
    T     = eltype(BSK.knots(basis))

    pieces = PolyPiece{T,P+1}[]

    intervals = poly_intervals(bfun)  
    for (left, right) in intervals
        push!(pieces, _mk_piece(Val(P), T(left), T(right)))
    end

    return pieces
end


"""
    centered_monomial_coeffs(S::BSplineKit.Spline, x_c)

Computes the coefficients for a centered polynomial representation via Taylor expansion of S around
x_c. returns the tuple of coefficients `(c₀, c₁, …, c_p)` such that on the interval
containing `x_c`,

    S(x) = ∑ₖ cₖ * (x - x_c)^k,

where `S` is a BSplineKit spline of degree `p`.

Each coefficient is computed as cₖ = S^{(k)}(x_c) / k!.
"""
function centered_monomial_coeffs(S::BSK.Spline{T}, x_c::T) where {T<:AbstractFloat}
    p = BSK.order(BSK.Splines.basis(S)) - 1   # degree

    return ntuple(p + 1) do k
        k == 1 ? S(x_c) : (BSK.Splines.Derivative(k - 1) * S)(x_c) / T(factorial(k - 1))
    end
end


####################################################
# Single B Spline Construction and Utilities
#####################################################

"""
    SingleBSpline{T,N,...}

Wraps a single B-spline basis function from a BSplineKit basis. The struct is
fully parametric in the wrapped BSplineKit object types (basis, basis function,
spline, and its derivative/antiderivative splines) so that all evaluations
dispatch statically; construct via `SingleBSpline(basis, j)` and let the
parameters be inferred.

Fields
- `basis`          : BSpline basis of which the spline is part
- `basis_function` : the b-spline as a `BSplineKit.BSplines.BasisFunction`
- `spline`         : the b-spline as a `BSplineKit.Spline{T}`
- `spline_anti_d`  : antiderivative of the spline
- `spline_d2`      : second derivative of the spline
- `spline_d4`      : fourth derivative of the spline (zero closure for p < 4)
- `j`              : basis index (1..n) in the parent basis
- `p`              : degree; N = p+1 is the number of monomial coeffs per piece
- `knots`          : full knot vector of the parent basis, including endpoint
                     multiplicities and any stacked interior knots
- `pieces`         : per-span polynomial pieces represented on [0,1]
- `support`        : 1 or 2 non-wrapping intervals in [0,1] (2 only if a
                     periodic support wraps around 0/1)
- `mass`           : total integral ∫₀¹ ϕ dx
"""
struct SingleBSpline{T,N,BAS,BF,SP,SPI,SPD2,SPD4}
    basis::BAS
    basis_function::BF 
    spline::SP
    spline_anti_d::SPI
    spline_d2::SPD2
    spline_d4::SPD4
    j::Int
    p::Int
    knots::Vector{T}
    pieces::Vector{PolyPiece{T,N}}
    support::Vector{NTuple{2,T}}
    mass::T
end

"""
Construct a SingleBSpline wrapper for the j-th basis function in `basis`.
"""
function SingleBSpline(basis::BAS, j::Int) where {BAS<:BSK.BSplines.AbstractBSplineBasis}
    T = eltype(BSK.BSplines.knots(basis))
    P = BSK.BSplines.order(basis) - 1   # degree
    N = P + 1                            # number of monomial coefficients

    # One-hot spline
    coeffs = zeros(T, length(basis))
    coeffs[j] = one(T)
    spline = BSK.Splines.Spline(basis, coeffs)
    spline_anti_d = BSK.Splines.integral(spline)
    mass = spline_anti_d(one(T)) - spline_anti_d(zero(T))

    # Derivatives
    D2  = (P ≥ 2) ? (BSK.Splines.Derivative(2) * spline) : x -> zero(T) # Loses spline metadata but we only need correct eval downstream
    D4  = (P ≥ 4) ? (BSK.Splines.Derivative(4) * spline) : x -> zero(T) # Loses spline metadata but we only need correct eval downstream

    # Basis function object
    bf = basis[j]

    # Build pieces (P-parametric) and fill in their centered-monomial coefficients
    pcs = polynomial_pieces(bf, Val(P))
    pcs_filled = PolyPiece{T,N}[with_coeffs(pce, centered_monomial_coeffs(spline, pce.x0))
                                for pce in pcs]

    #support interval(s)
    support = Utils.union_intervals(poly_intervals(bf))

    return SingleBSpline{T,N, typeof(basis), typeof(bf), typeof(spline), typeof(spline_anti_d), typeof(D2), typeof(D4)}(
        basis, bf, spline, spline_anti_d, D2, D4, j, P, collect(T, BSK.BSplines.knots(basis)), pcs_filled, support, mass
    )
end


# evaluation, derivative evaluation
@inline (ϕ::SingleBSpline{T,N,BAS,BF,SP})(x::T) where {T<:AbstractFloat,N,BAS,BF,SP} =
    ϕ.basis_function(x)

    
@inline function evaluate(ϕ::SingleBSpline{T,N,BAS,BF,SP}, x::T) :: T where {T<:AbstractFloat,N,BAS,BF,SP}
    return ϕ(x)
end

@inline function first_derivative(ϕ::SingleBSpline{T,N,BAS,BF,SP}, x::T)::T where {T<:AbstractFloat,N,BAS,BF,SP}
    return (BSK.Splines.Derivative(1) * ϕ.spline)(x)
end

@inline function second_derivative(ϕ::SingleBSpline{T,N,BAS,BF,SP,SPD2}, x::T)::T where {T<:AbstractFloat,N,BAS,BF,SP,SPD2}
    return ϕ.spline_d2(x)
end


"""
build_single_splines(basis::B) where {B<:BSK.BSplines.AbstractBSplineBasis}

Constructs all SingleBSpline objects for the given B-spline basis. Returns a
vector of SingleBSpline{T,N} objects, where T is the floating-point type of the
knots and N = degree+1.
"""
function build_single_splines(basis::B) where  {B<:BSK.BSplines.AbstractBSplineBasis}
    # Comprehension yields a concretely-typed vector (all SingleBSplines from one
    # basis share the same type parameters), avoiding dynamic dispatch downstream.
    return [SingleBSpline(basis, j) for j in 1:length(basis)]
end


"""
    integrate_bspline(ϕ::SingleBSpline{T}, a::T, b::T, nodes, weights) -> T
    integrate_bspline(ϕ::SingleBSpline{T}, intervals, nodes, weights)  -> T
    integrate_bspline(ϕ, a, b)          -> T   # convenience, computes the GL rule internally
    integrate_bspline(ϕ, intervals)     -> T   # convenience

Compute ∫ₐᵇ ϕ(x) dx exactly by splitting [a, b] at the knots of ϕ and applying
Gauss-Legendre quadrature on each knot-free piece, where ϕ is a single
polynomial of degree `ϕ.p`.

The `intervals` form accepts a `Tuple` of `(a, b)` pairs or an `AbstractVector` of pairs, and
returns the sum of the single-interval integrals.

Arguments
---------
- `ϕ`               : the B-spline wrapper (knots sorted, values in [0,1])
- `a`, `b`          : integration limits with 0 ≤ a ≤ b ≤ 1 (non-wrapping)
- `nodes`, `weights`: Gauss-Legendre rule on [-1,1] in type `T` with
                      `length(nodes) ≥ cld(ϕ.p + 1, 2)` for exactness
                      (generate once via `legendre(BigFloat, n)` and cast to `T`,
                      as elsewhere in the package). The convenience methods
                      without `nodes`/`weights` compute this rule per call —
                      fine for tests/scripts, avoid in hot loops.
"""
function integrate_bspline(
    ϕ       :: SingleBSpline{T},
    a       :: T,
    b       :: T,
    nodes   :: Vector{T},
    weights :: Vector{T},
) ::T where {T<:AbstractFloat}

    (zero(T) <= a <= b <= one(T)) ||
        throw(ArgumentError("Require 0 ≤ a ≤ b ≤ 1, got a=$a, b=$b"))
    length(nodes) >= cld(ϕ.p + 1, 2) ||
        throw(ArgumentError("Insufficient Gauss-Legendre nodes for exactness: " *
                            "need ≥ $(cld(ϕ.p + 1, 2)) for degree p=$(ϕ.p), got $(length(nodes))."))
    a == b && return zero(T)

    knots = ϕ.knots
    total = zero(T)

    for (sa, sb) in ϕ.support
        lo = max(a, sa)
        hi = min(b, sb)
        hi <= lo && continue

        # Knots strictly inside (lo, hi); duplicates from stacked multiplicities
        # produce zero-width pieces, which the `k > left` guard skips.
        i1 = searchsortedlast(knots, lo) + 1     # first knot > lo
        i2 = searchsortedfirst(knots, hi) - 1    # last knot < hi

        left = lo
        @inbounds for idx in i1:i2
            k = knots[idx]
            if k > left
                total += Utils._gl_integrate(ϕ, left, k, nodes, weights)
                left = k
            end
        end
        if hi > left
            total += Utils._gl_integrate(ϕ, left, hi, nodes, weights)
        end
    end

    return total
end

function integrate_bspline(
    ϕ         :: SingleBSpline{T},
    intervals :: Union{Tuple{Vararg{NTuple{2,T}}}, AbstractVector{NTuple{2,T}}},
    nodes     :: Vector{T},
    weights   :: Vector{T},
) ::T where {T<:AbstractFloat}
    total = zero(T)
    for (a, b) in intervals
        total += integrate_bspline(ϕ, a, b, nodes, weights)
    end
    return total
end

# Convenience methods: compute the minimal exact GL rule per call.
function integrate_bspline(ϕ::SingleBSpline{T}, a::T, b::T) ::T where {T<:AbstractFloat}
    ξ, ω = legendre(BigFloat, cld(ϕ.p + 1, 2))
    return integrate_bspline(ϕ, a, b, T.(ξ), T.(ω))
end

function integrate_bspline(
    ϕ         :: SingleBSpline{T},
    intervals :: Union{Tuple{Vararg{NTuple{2,T}}}, AbstractVector{NTuple{2,T}}},
) ::T where {T<:AbstractFloat}
    ξ, ω = legendre(BigFloat, cld(ϕ.p + 1, 2))
    return integrate_bspline(ϕ, intervals, T.(ξ), T.(ω))
end


"""
    merge_breakpoints(pts1, pts2; atol=eps(T)) -> Vector{T}

Merge two sorted `AbstractVector`s of breakpoints into one sorted, deduplicated
`Vector{T}`. Points within `atol` of each other are collapsed to the first occurrence.

Used wherever a union mesh of two knot vectors is needed, e.g. for integrating a
product of two piecewise-polynomial functions on different knot grids.
"""
function merge_breakpoints(
    pts1::AbstractVector{T},
    pts2::AbstractVector{T};
    atol::T = eps(T),
) ::Vector{T} where {T<:AbstractFloat}
    out = T[]
    sizehint!(out, length(pts1) + length(pts2))
    i = j = 1
    prev = typemin(T)
    while i ≤ length(pts1) || j ≤ length(pts2)
        val = if j > length(pts2) || (i ≤ length(pts1) && pts1[i] ≤ pts2[j])
            v = pts1[i]; i += 1; v
        else
            v = pts2[j]; j += 1; v
        end
        if val - prev > atol
            push!(out, val)
            prev = val
        end
    end
    return out
end


"""
    convert_precision(ϕ::SingleBSpline{T}, ::Type{S}) -> SingleBSpline{S}
    convert_precision(splines::Vector{<:SingleBSpline{T}}, ::Type{S}) -> Vector{SingleBSpline{S}}

Reconstruct a `SingleBSpline` (or a vector of SingleBSplines) in floating-point
type `S`. The full knot vector (including endpoint multiplicities and any stacked
interior knots) is stored in `ϕ.knots`; passing it with `augment=Val(false)` to
`BSplineBasis` reproduces the identical multiplicity structure in type `S`.

All polynomial coefficients, the antiderivative, and derivative splines are
recomputed entirely in `S` — no rounding is inherited from `T`.

If `T === S` the input is returned unchanged (no copy).
"""
function convert_precision(ϕ::SingleBSpline{T}, ::Type{S}) where {T, S<:AbstractFloat}
    T === S && return ϕ
    new_knots = S.(ϕ.knots)
    new_basis = BSK.BSplineBasis(BSK.BSplineOrder(ϕ.p + 1), new_knots; augment=Val(false))
    return SingleBSpline(new_basis, ϕ.j)
end

function convert_precision(splines::Vector{<:SingleBSpline{T}}, ::Type{S}) where {T, S<:AbstractFloat}
    T === S && return splines
    ϕ1        = splines[1]
    new_knots = S.(ϕ1.knots)
    new_basis = BSK.BSplineBasis(BSK.BSplineOrder(ϕ1.p + 1), new_knots; augment=Val(false))
    return [SingleBSpline(new_basis, j) for j in 1:length(splines)]
end


"""
    build_pm_basis(α::Real, ε::Real, n_outer::Integer, ::Type{T}=Float64;
                   p::Int=3, decouple::Bool=false)

Constructs the B-spline basis for the noisy Pomeau-Manneville map.

If `decouple == false`, returns a standard a spline basis with splines whose supports may straddle
    the boundary layer cutoffs L_ε and 1-L_ε.
If `decouple == true`, returns a basis of splines whose supports are strictly contained in either
    [0,L_ε], [L_ε,1-L_ε], or [1-L_ε,1].

Returns:
- `basis` : The `BSplineBasis` object.
- `L_ε`     : The exact boundary layer scale computed for these parameters.
"""
function build_pm_basis(
    α::Real,
    ε::Real,
    n_outer::Integer,
    ::Type{T}=Float64;
    p::Int=3,
    decouple::Bool=false,
    bdry_layer_constant::T=one(T)
) where {T<:AbstractFloat}

    breaks = hybrid_equidistribution_breakpoints(α, ε, n_outer, T)

    α_T = T(α)
    L_ε   = Utils.boundary_layer_scale(α_T, T(ε))

    if !decouple
        basis = BSK.BSplineBasis(BSplineOrder(p + 1), copy(breaks))
    else
        stack_targets = T[L_ε, one(T) - L_ε]
        knots = build_stacked_knot_vector(breaks, stack_targets; p=p)
        basis = BSK.BSplineBasis(BSplineOrder(p + 1), knots; augment=Val(false))
    end

    return basis, L_ε
end

# -------------------------------------------------
# --- L1 Norm of Difference Between Two Splines ---
# -------------------------------------------------


"""
    l1_norm_difference(splines, c1, c2; atol) -> T
    l1_norm_difference(basis, c1, c2; atol) -> T
    l1_norm_difference(splines1, c1, splines2, c2; atol) -> T
    l1_norm_difference(basis1, c1, basis2, c2; atol) -> T

Compute

    ∫₀¹ |f(x) - g(x)| dx,

where `f` and `g` are linear combinations of B-splines of the same degree.

The calculation uses the piecewise-polynomial structure directly. The two
splines are partitioned into common polynomial spans, their difference is
formed exactly on each span, and the absolute value is integrated by splitting
at its roots.

## Arguments

- `basis` / `splines` :
    Shared B-spline basis or prebuilt `SingleBSpline` objects.

- `basis1`, `basis2` :
    Two B-spline bases of the same order.

- `c1`, `c2` :
    Coefficient vectors defining the two splines.

- `atol` :
    Tolerance used when merging nearby breakpoints, stripping negligible
    leading polynomial coefficients, and skipping degenerate intervals.

# Extended help
## Algorithm

1. Construct the two spline functions `f` and `g`.

2. Merge the distinct knot locations of the two bases to form a common
   partition

       0 = x₀ < x₁ < ... < xₙ = 1.

   The merged knots are used only to determine polynomial spans. The original
   B-spline bases are not modified.

3. On each common span `[a,b]`, neither spline has an interior knot, so both
   `f` and `g` are single degree-`P` polynomials. At the midpoint

       x_c = (a + b) / 2,

   `centered_monomial_coeffs` gives the exact local representations

       f(x) = Σₖ fₖ (x - x_c)^k,
       g(x) = Σₖ gₖ (x - x_c)^k.

   Because both expansions use the same center, subtracting their coefficient
   vectors gives the exact polynomial representation of `f - g` on `[a,b]`.

4. Find the interior roots of `f - g` using `_centpoly_roots_in`. These roots
   divide `[a,b]` into subintervals on which `f - g` has constant sign.

5. On each root-free subinterval,

       ∫ |f - g| = |∫ (f - g)|.

   Since `f - g` is a degree-`P` polynomial there, Gauss-Legendre quadrature
   with `ceil((P+1)/2)` nodes evaluates the integral exactly.

The same algorithm is used whether the two splines share a basis or come from
different bases. The current root solver supports polynomial degree at most
three.
"""
function l1_norm_difference end


# Core implementation: two possibly different B-spline bases.
function l1_norm_difference(
    basis1 :: BSK.BSplines.AbstractBSplineBasis,
    c1     :: AbstractVector{T},
    basis2 :: BSK.BSplines.AbstractBSplineBasis,
    c2     :: AbstractVector{T};
    atol   :: T = eps(T),
) ::T where {T<:AbstractFloat}

    length(c1) == length(basis1) ||
        throw(ArgumentError(
            "c1 must have length $(length(basis1)); got $(length(c1))"
        ))

    length(c2) == length(basis2) ||
        throw(ArgumentError(
            "c2 must have length $(length(basis2)); got $(length(c2))"
        ))

    order = BSK.BSplines.order(basis1)
    BSK.BSplines.order(basis2) == order ||
        throw(ArgumentError(
            "bases must have the same B-spline order; got " *
            "$order and $(BSK.BSplines.order(basis2))"
        ))

    P = order - 1
    P ≤ 3 ||
        throw(ArgumentError(
            "l1_norm_difference currently supports degree ≤ 3; got degree $P"
        ))

    # Construct the original splines. They remain in their own bases throughout
    # the calculation; no interpolation onto a common basis is performed.
    S1 = BSK.Splines.Spline(basis1, c1)
    S2 = BSK.Splines.Spline(basis2, c2)

    # Merge knot locations only to determine intervals on which both splines
    # are single polynomials. Repeated/stacked knots remain part of the original
    # bases; their multiplicities are not altered.
    knots1 = T[
        x for x in BSK.knots(basis1)
        if zero(T) <= x <= one(T)
    ]
    knots2 = T[
        x for x in BSK.knots(basis2)
        if zero(T) <= x <= one(T)
    ]

    breaks = merge_breakpoints(knots1, knots2; atol=atol)

    length(breaks) ≥ 2 ||
        throw(ArgumentError("bases must contain knots spanning [0,1]"))

    abs(breaks[1]) ≤ atol ||
        throw(ArgumentError("bases must contain the left endpoint 0"))

    abs(breaks[end] - one(T)) ≤ atol ||
        throw(ArgumentError("bases must contain the right endpoint 1"))

    # Make the integration endpoints exact after the tolerance checks above.
    breaks[1]   = zero(T)
    breaks[end] = one(T)

    # A degree-P polynomial is integrated exactly by n-point Gauss-Legendre
    # quadrature whenever 2n - 1 ≥ P.
    n_gl = (P + 2) ÷ 2
    ξB, ωB = legendre(BigFloat, n_gl)
    nodes   = T.(ξB)
    weights = T.(ωB)

    total = zero(T)

    for k in 1:length(breaks)-1
        a = breaks[k]
        b = breaks[k+1]

        b - a ≤ atol && continue

        # Since [a,b] contains no interior knot from either basis, S1 and S2
        # are each a single polynomial on this entire span. Expanding both
        # about the same midpoint lets us subtract their coefficients directly.
        x0 = (a + b) / T(2)

        coeffs1 = centered_monomial_coeffs(S1, x0)
        coeffs2 = centered_monomial_coeffs(S2, x0)

        c_span = T[
            coeffs1[m] - coeffs2[m]
            for m in 1:P+1
        ]

        # Work in the shifted coordinate t = x - x0.
        da = a - x0
        db = b - x0

        roots = _centpoly_roots_in(c_span, da, db, atol)
        pts   = vcat(da, roots, db)

        # Between consecutive roots the polynomial has constant sign, so
        # ∫|p| = |∫p| and the Gauss-Legendre rule is exact.
        @inbounds for m in 1:length(pts)-1
            u = pts[m]
            v = pts[m+1]

            v - u ≤ atol && continue

            total += abs(
                Utils._gl_integrate(
                    t -> evalpoly(t, c_span),
                    u,
                    v,
                    nodes,
                    weights,
                )
            )
        end
    end

    return total
end


# Shared-basis form: use the same general algorithm with basis1 === basis2.
function l1_norm_difference(
    basis :: BSK.BSplines.AbstractBSplineBasis,
    c1    :: AbstractVector{T},
    c2    :: AbstractVector{T};
    kwargs...
) where {T<:AbstractFloat}

    return l1_norm_difference(basis, c1, basis, c2; kwargs...)
end


# Prebuilt SingleBSpline form with a shared basis.
function l1_norm_difference(
    splines :: Vector{<:SingleBSpline{T}},
    c1      :: AbstractVector{T},
    c2      :: AbstractVector{T};
    kwargs...
) where {T<:AbstractFloat}

    isempty(splines) &&
        throw(ArgumentError("spline vector must be non-empty"))

    return l1_norm_difference(
        splines[1].basis,
        c1,
        c2;
        kwargs...
    )
end


# Prebuilt SingleBSpline form with two possibly different bases.
function l1_norm_difference(
    splines1 :: Vector{<:SingleBSpline{T}},
    c1       :: AbstractVector{T},
    splines2 :: Vector{<:SingleBSpline{T}},
    c2       :: AbstractVector{T};
    kwargs...
) where {T<:AbstractFloat}

    isempty(splines1) &&
        throw(ArgumentError("splines1 must be non-empty"))

    isempty(splines2) &&
        throw(ArgumentError("splines2 must be non-empty"))

    return l1_norm_difference(
        splines1[1].basis,
        c1,
        splines2[1].basis,
        c2;
        kwargs...
    )
end


"""
    _centpoly_roots_in(c, da, db, atol) -> Vector{T}

Find interior breakpoints for the centered monomial polynomial

    p(Δx) = c[1] + c[2]·Δx + c[3]·Δx² + … + c[P+1]·Δx^P,

where `Δx = x - x0` is the coordinate relative to the span midpoint `x0`.
The arguments `da = a - x0 < 0` and `db = b - x0 > 0` are the span endpoints
`[a, b]` expressed in these same shifted coordinates. Breakpoints are returned
in shifted coordinates.

These breakpoints are used to partition the span when integrating `|p|`. The
important requirement is therefore that no root at which `p` changes sign is
missed. Additional breakpoints are harmless, since subdividing an interval on
which `p` has constant sign does not change

    ∫ |p(x)| dx = |∫ p(x) dx|.

Accordingly, the routine may conservatively return a point that is not an exact
root when the discriminant is numerically close to zero.

The effective degree is determined by stripping trailing coefficients smaller
than `atol * max(1, ‖c‖∞)`. Breakpoints within `atol` of an endpoint are
excluded.

**Algorithm**:
- Degree 0: no breakpoints.
- Degree 1: direct formula `r = -c[1]/c[2]`.
- Degree 2: standard quadratic formula. If the discriminant is numerically
  indistinguishable from zero, the quadratic vertex is retained as a
  conservative breakpoint.
- Degree 3: delegates to `_cubic_roots_in`, which uses the critical points of
  the cubic to partition the span into monotone intervals and locates every
  sign-changing root by bisection.

Errors if the effective degree exceeds 3.
"""
function _centpoly_roots_in(
    c    :: Vector{T},
    da   :: T,
    db   :: T,
    atol :: T,
) ::Vector{T} where {T<:AbstractFloat}

    p     = length(c) - 1
    scale = max(one(T), maximum(abs, c))

    while p > 0 && abs(c[p + 1]) < atol * scale
        p -= 1
    end

    _in(r) = da + atol < r < db - atol

    p == 0 && return T[]

    if p == 1
        r = -c[1] / c[2]
        return _in(r) ? T[r] : T[]
    end

    if p == 2
        A, B, C = c[3], c[2], c[1]
        disc = B^2 - T(4) * A * C

        scale_disc = B^2 + T(4) * abs(A * C) + eps(T)
        tol_disc   = T(1e3) * eps(T) * scale_disc

        disc < -tol_disc && return T[]

        inv2A = inv(T(2) * A)

        # If the discriminant is numerically close to zero, there may be either
        # no real root or one repeated real root. Since these points are used
        # only as integration breakpoints, conservatively retain the vertex.
        if disc <= tol_disc
            r = -B * inv2A
            return _in(r) ? T[r] : T[]
        end

        sq = sqrt(disc)
        return sort!(filter(_in, [
            (-B - sq) * inv2A,
            (-B + sq) * inv2A,
        ]))
    end

    p == 3 ||
        error("_centpoly_roots_in: degree $p > 3 not supported")

    return _cubic_roots_in(
        c[1],
        c[2],
        c[3],
        c[4],
        da,
        db,
        atol,
    )
end


"""
    _cubic_roots_in(C0, C1, C2, C3, da, db, atol) -> Vector{T}

Find interior breakpoints for the cubic

    p(t) = C3·t³ + C2·t² + C1·t + C0

on `(da, db)`.

This routine is used to partition the span when integrating `|p|`. The
important requirement is that no root at which `p` changes sign is missed;
additional breakpoints are harmless.

The critical points of the cubic are the roots of

    p'(t) = 3C3·t² + 2C2·t + C1.

They partition the interval into pieces on which `p` is monotone. The critical
points are found using `_centpoly_roots_in` and retained as conservative
breakpoints. On each monotone interval whose endpoint values have opposite
signs, the unique sign-changing root is located using a bracketed root solve.

Returned breakpoints are sorted and lie at least `atol` away from the span
endpoints.
"""
function _cubic_roots_in(
    C0   :: T,
    C1   :: T,
    C2   :: T,
    C3   :: T,
    da   :: T,
    db   :: T,
    atol :: T,
) ::Vector{T} where {T<:AbstractFloat}

    _in(r) = da + atol < r < db - atol
    f(t)   = ((C3 * t + C2) * t + C1) * t + C0

    # Critical points are the roots of
    # p'(t) = C1 + 2C2*t + 3C3*t².
    dc   = T[C1, T(2) * C2, T(3) * C3]
    crit = _centpoly_roots_in(dc, da, db, atol)

    # Critical points are conservative integration breakpoints.
    roots = copy(crit)
    pts   = vcat(da, crit, db)

    @inbounds for k in 1:length(pts)-1
        a  = pts[k]
        b  = pts[k+1]
        fa = f(a)
        fb = f(b)

        if (fa < zero(T) && fb > zero(T)) ||
           (fa > zero(T) && fb < zero(T))

            r = find_zero(f, (a, b), Bisection(); xatol=atol)
            _in(r) && push!(roots, r)
        end
    end

    return sort!(roots)
end
